"""Setup tables

Revision ID: 90e9e988474d
Revises: 
Create Date: 2025-11-08 20:07:43.624186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import Database

# revision identifiers, used by Alembic.
revision: str = '90e9e988474d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_decks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarot_decks')),
    sa.UniqueConstraint('name', name=op.f('uq_tarot_decks_name'))
    )
    op.create_table('tarot_cards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('meaning_upright', sa.Text(), nullable=True),
    sa.Column('meaning_reversed', sa.Text(), nullable=True),
    sa.Column('upright_keywords', sa.Text(), nullable=True),
    sa.Column('reversed_keywords', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['tarot_decks.id'], name=op.f('fk_tarot_cards_deck_id_tarot_decks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarot_cards')),
    sa.UniqueConstraint('deck_id', 'name', name='uq_tarot_deck_identifiers')
    )
    op.create_index(op.f('ix_tarot_cards_canonical_id'), 'tarot_cards', ['canonical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarot_cards_canonical_id'), table_name='tarot_cards')
    op.drop_table('tarot_cards')
    op.drop_table('tarot_decks')
    # ### end Alembic commands ###
