from discord    import PartialEmoji
################################################################################

__all__ = ("BotEmojis", )

################################################################################
class BotEmojis:
    """A class to store the bot's emoji requirements as PartialEmoji objects."""

    ArrowDown = PartialEmoji.from_str("⬇️")
    ArrowLeft = PartialEmoji.from_str("⬅️")
    ArrowRight = PartialEmoji.from_str("➡️")
    Asterisk = PartialEmoji.from_str("*️⃣")
    Bell = PartialEmoji.from_str("🔔")
    Button = PartialEmoji.from_str("🔘")
    Camera = PartialEmoji.from_str("<:camera:958816462406033498>")
    Check = PartialEmoji.from_str("<:check:958615684869414962>")
    CheckGreen = PartialEmoji.from_str("<:CheckGreen:1280639745818624052>")
    CheckGray = PartialEmoji.from_str("<:CheckGray:1280639747340894278>")
    Clock = PartialEmoji.from_str("🕒")
    ColorPalette = PartialEmoji.from_str("🎨")
    Construction = PartialEmoji.from_str("🚧")
    Cross = PartialEmoji.from_str("<:Cross:1409011214339538995>")
    CrossOld = PartialEmoji.from_str("❌")
    Cycle = PartialEmoji.from_str("🔄")
    Diamond = PartialEmoji.from_str("💠")
    Drum = PartialEmoji.from_str("🥁")
    EmojiMonocle = PartialEmoji.from_str("🧐")
    Envelope = PartialEmoji.from_str("💌")
    EnvelopeWithArrow = PartialEmoji.from_str("📤")
    Eye = PartialEmoji.from_str("👁️")
    Eyes = PartialEmoji.from_str("👀")
    FlyingEnvelope = PartialEmoji.from_str("📨")
    FlyingMoney = PartialEmoji.from_str("💸")
    Gear = PartialEmoji.from_str("⚙️")
    Globe = PartialEmoji.from_str("🌐")
    Goose = PartialEmoji.from_str("<:goose:958828235058208829>")
    House = PartialEmoji.from_str("🏠")
    Image = PartialEmoji.from_str("🖼️")
    Letters = PartialEmoji.from_str("🔤")
    Lock = PartialEmoji.from_str("🔒")
    Minus = PartialEmoji.from_str("➖")
    Numbers = PartialEmoji.from_str("🔢")
    Paper = PartialEmoji.from_str("📝")
    PartyPopper = PartialEmoji.from_str("🎉")
    Pause = PartialEmoji.from_str("<:Pause:1186526919940902912>")
    Pencil = PartialEmoji.from_str("✏️")
    PencilAndPaper = PartialEmoji.from_str("📝")
    Plus = PartialEmoji.from_str("➕")
    QuestionMark = PartialEmoji.from_str("❓")
    Scroll = PartialEmoji.from_str("📜")
    Silhouette = PartialEmoji.from_str("👥")
    Sleep = PartialEmoji.from_str("💤")
    Sparkle = PartialEmoji.from_str("✨")
    Star = PartialEmoji.from_str("⭐")
    Stopwatch = PartialEmoji.from_str("⏱️")
    Text = PartialEmoji.from_str("🔠")
    ThumbsDown = PartialEmoji.from_str("👎")
    ThumbsUp = PartialEmoji.from_str("👍")
    Trash = PartialEmoji.from_str("🗑️")
    Unlock = PartialEmoji.from_str("🔓")
    Warning = PartialEmoji.from_str("⚠️")

################################################################################
